version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SQL#1234
    ports:
      - "1433:1433"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    depends_on:
      - sql-server
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:1.13.6
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /data/nginx/cache
    ports:
      - "80:80"
    depends_on:
      - node-app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
